<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Club;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;

class LedgerController extends Controller
{
    public function index(Club $club)
    {
        $this->authorizeClub($club);
        $filters = $this->parseFilters();
        $data    = $this->buildLedgerData($club, $filters);
        return view('admin.ledger.index', array_merge(['club' => $club, 'filters' => $filters], $data));
    }

    public function export(Club $club)
    {
        $this->authorizeClub($club);
        $filters     = $this->parseFilters();
        $data        = $this->buildLedgerData($club, $filters);
        $generatedAt = now()->format('d M Y H:i');
        $generatedBy = auth()->user()->name;

        $filename = sprintf(
            '%s-ledger-%s-to-%s.csv',
            str_replace(' ', '-', strtolower($club->name)),
            $filters['from']->format('Y-m-d'),
            $filters['to']->format('Y-m-d')
        );

        $headers = [
            'Content-Type'        => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Cache-Control'       => 'no-store, no-cache',
        ];

        $callback = function () use ($club, $filters, $data, $generatedAt, $generatedBy) {
            $h = fopen('php://output', 'w');
            fputs($h, "\xEF\xBB\xBF"); // UTF-8 BOM for Excel

            // ── Report header ─────────────────────────────────────────────
            fputcsv($h, ['CLUB FINANCIAL LEDGER REPORT']);
            fputcsv($h, ['Club', $club->name]);
            fputcsv($h, ['Period', $filters['from']->format('d M Y') . ' — ' . $filters['to']->format('d M Y')]);
            fputcsv($h, ['Generated', $generatedAt]);
            fputcsv($h, ['Generated By', $generatedBy]);
            fputcsv($h, ['Opening Balance (RM)', number_format($filters['openingBalance'], 2)]);
            fputcsv($h, []);

            // ── Summary ───────────────────────────────────────────────────
            fputcsv($h, ['SUMMARY']);
            fputcsv($h, ['Total Income (RM)',   number_format($data['totalIncome'], 2)]);
            fputcsv($h, ['Total Expenses (RM)', number_format($data['totalExpenses'], 2)]);
            fputcsv($h, ['Net Movement (RM)',   number_format($data['totalIncome'] - $data['totalExpenses'], 2)]);
            fputcsv($h, ['Closing Balance (RM)', number_format($data['closingBalance'], 2)]);
            fputcsv($h, []);

            // ── Monthly breakdown ─────────────────────────────────────────
            fputcsv($h, ['MONTHLY BREAKDOWN']);
            fputcsv($h, ['Month', 'Income (RM)', 'Expenses (RM)', 'Net (RM)', 'Running Balance (RM)']);
            foreach ($data['monthlySummary'] as $row) {
                fputcsv($h, [
                    $row['month'],
                    number_format($row['income'], 2),
                    number_format($row['expenses'], 2),
                    number_format($row['net'], 2),
                    number_format($row['balance'], 2),
                ]);
            }
            fputcsv($h, []);

            // ── Transactions ──────────────────────────────────────────────
            fputcsv($h, ['TRANSACTIONS']);
            fputcsv($h, ['#', 'Date', 'Type', 'Description', 'Member / Category', 'Reference', 'Amount In (RM)', 'Amount Out (RM)', 'Running Balance (RM)']);
            foreach ($data['transactions'] as $i => $t) {
                fputcsv($h, [
                    $i + 1,
                    $t['date'],
                    $t['type'],
                    $t['description'],
                    $t['party'],
                    $t['reference'],
                    $t['amount_in']  !== null ? number_format($t['amount_in'],  2) : '',
                    $t['amount_out'] !== null ? number_format($t['amount_out'], 2) : '',
                    number_format($t['balance'], 2),
                ]);
            }
            fputcsv($h, []);

            // ── Outstanding ───────────────────────────────────────────────
            $hasOutstanding = $data['overduePayments']->isNotEmpty() || $data['pendingPayments']->isNotEmpty();
            if ($hasOutstanding) {
                fputcsv($h, ['OUTSTANDING PAYMENTS (all time)']);

                if ($data['overduePayments']->isNotEmpty()) {
                    fputcsv($h, ['OVERDUE']);
                    fputcsv($h, ['#', 'Member', 'Period', 'Due Date', 'Amount (RM)']);
                    foreach ($data['overduePayments'] as $i => $p) {
                        fputcsv($h, [$i + 1, $p->user->name, $p->period_start->format('M Y'), $p->due_date->format('d M Y'), number_format($p->amount, 2)]);
                    }
                    fputcsv($h, ['', '', '', 'TOTAL OVERDUE (RM)', number_format($data['overduePayments']->sum('amount'), 2)]);
                    fputcsv($h, []);
                }

                if ($data['pendingPayments']->isNotEmpty()) {
                    fputcsv($h, ['PENDING']);
                    fputcsv($h, ['#', 'Member', 'Period', 'Due Date', 'Amount (RM)']);
                    foreach ($data['pendingPayments'] as $i => $p) {
                        fputcsv($h, [$i + 1, $p->user->name, $p->period_start->format('M Y'), $p->due_date->format('d M Y'), number_format($p->amount, 2)]);
                    }
                    fputcsv($h, ['', '', '', 'TOTAL PENDING (RM)', number_format($data['pendingPayments']->sum('amount'), 2)]);
                }
            }

            fclose($h);
        };

        return response()->stream($callback, 200, $headers);
    }

    public function exportPdf(Club $club)
    {
        $this->authorizeClub($club);
        $filters     = $this->parseFilters();
        $data        = $this->buildLedgerData($club, $filters);
        $generatedAt = now()->format('d M Y H:i');
        $generatedBy = auth()->user()->name;

        $pdf = Pdf::loadView('admin.ledger.pdf', array_merge(
            ['club' => $club, 'filters' => $filters, 'generatedAt' => $generatedAt, 'generatedBy' => $generatedBy],
            $data
        ))->setPaper('a4', 'landscape');

        $filename = sprintf(
            '%s-ledger-%s-to-%s.pdf',
            str_replace(' ', '-', strtolower($club->name)),
            $filters['from']->format('Y-m-d'),
            $filters['to']->format('Y-m-d')
        );

        return $pdf->download($filename);
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private function parseFilters(): array
    {
        // Validate all three inputs before touching them
        request()->validate([
            'from'            => 'nullable|date_format:Y-m-d',
            'to'              => 'nullable|date_format:Y-m-d',
            'opening_balance' => 'nullable|numeric|min:0|max:999999999.99',
        ]);

        $from = request('from')
            ? Carbon::createFromFormat('Y-m-d', request('from'))->startOfDay()
            : Carbon::now()->startOfYear();

        $to = request('to')
            ? Carbon::createFromFormat('Y-m-d', request('to'))->endOfDay()
            : Carbon::now()->endOfDay();

        if ($from->gt($to)) {
            $from = $to->copy()->startOfYear();
        }

        $openingBalance = (float) request('opening_balance', 0);

        return compact('from', 'to', 'openingBalance');
    }

    private function buildLedgerData(Club $club, array $filters): array
    {
        ['from' => $from, 'to' => $to, 'openingBalance' => $openingBalance] = $filters;

        // ── Income: paid payments within the date range ───────────────────
        $payments = $club->payments()
            ->with('user')
            ->where('status', 'paid')
            ->whereBetween('paid_date', [$from->toDateString(), $to->toDateString()])
            ->orderBy('paid_date')->orderBy('id')
            ->get();

        // ── Expenses within the date range ────────────────────────────────
        $expenses = $club->expenses()
            ->with('category')
            ->whereBetween('expense_date', [$from->toDateString(), $to->toDateString()])
            ->orderBy('expense_date')->orderBy('id')
            ->get();

        // ── Merge into chronological rows ─────────────────────────────────
        $rows = collect();

        foreach ($payments as $p) {
            $rows->push([
                'sort_key'   => $p->paid_date->format('Y-m-d') . 'A' . str_pad($p->id, 10, '0', STR_PAD_LEFT),
                'date'       => $p->paid_date->format('Y-m-d'),
                'type'       => 'Income',
                'description'=> 'Fee payment (' . $p->frequency . ') — ' . $p->period_start->format('M Y'),
                'party'      => $p->user->name,
                'reference'  => $p->reference ?? '',
                'amount_in'  => (float) $p->amount,
                'amount_out' => null,
                'balance'    => 0.0,
            ]);
        }

        foreach ($expenses as $e) {
            $rows->push([
                'sort_key'   => $e->expense_date->format('Y-m-d') . 'B' . str_pad($e->id, 10, '0', STR_PAD_LEFT),
                'date'       => $e->expense_date->format('Y-m-d'),
                'type'       => 'Expense',
                'description'=> $e->description,
                'party'      => $e->category->name,
                'reference'  => '',
                'amount_in'  => null,
                'amount_out' => (float) $e->amount,
                'balance'    => 0.0,
            ]);
        }

        $rows = $rows->sortBy('sort_key')->values();

        // Compute running balance
        $runBalance = $openingBalance;
        foreach ($rows as &$row) {
            $runBalance += ($row['amount_in'] ?? 0) - ($row['amount_out'] ?? 0);
            $row['balance'] = $runBalance;
        }
        unset($row);

        $totalIncome   = (float) $payments->sum('amount');
        $totalExpenses = (float) $expenses->sum('amount');
        $closingBalance = $openingBalance + $totalIncome - $totalExpenses;

        // ── Monthly breakdown ─────────────────────────────────────────────
        $monthlySummary   = [];
        $current          = $from->copy()->startOfMonth();
        $endMonth         = $to->copy()->startOfMonth();
        $monthRunBalance  = $openingBalance;

        while ($current->lte($endMonth)) {
            $key      = $current->format('Y-m');
            $monthInc = $rows->where('type', 'Income')
                ->filter(fn($r) => str_starts_with($r['date'], $key))
                ->sum('amount_in');
            $monthExp = $rows->where('type', 'Expense')
                ->filter(fn($r) => str_starts_with($r['date'], $key))
                ->sum('amount_out');
            $monthRunBalance += $monthInc - $monthExp;

            $monthlySummary[] = [
                'month'    => $current->format('M Y'),
                'income'   => (float) $monthInc,
                'expenses' => (float) $monthExp,
                'net'      => (float) ($monthInc - $monthExp),
                'balance'  => (float) $monthRunBalance,
            ];
            $current->addMonth();
        }

        // ── Outstanding (all-time, not date-filtered) ─────────────────────
        $pendingPayments = $club->payments()->with('user')
            ->where('status', 'pending')->orderBy('due_date')->get();

        $overduePayments = $club->payments()->with('user')
            ->where('status', 'overdue')->orderBy('due_date')->get();

        $transactions = $rows->all();

        return compact(
            'transactions',
            'totalIncome',
            'totalExpenses',
            'closingBalance',
            'monthlySummary',
            'pendingPayments',
            'overduePayments',
        );
    }

    private function authorizeClub(Club $club): void
    {
        $user = auth()->user();
        if ($user->isSuperAdmin()) {
            return;
        }
        abort_unless(
            $user->clubs()->wherePivot('role', 'admin')->where('clubs.id', $club->id)->exists(),
            403
        );
    }
}
